name: cahrehn's blog
description: Saying things about things
meta_description: "Saying things about things."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'http://www.cahrehn.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://www.cahrehn.com/blog'
author:         'cahrehn'
